spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://localhost:8090/
          predicates:
            - Path=/livres/**
        - id : r2
          uri: http://localhost:8091/
          predicates:
            - Path=/users/**
  application:
    name: gateway-service
server:
  port: 8888