spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://localhost:8090/
          predicates:
            - Path=/livres/**
          metadata:
           cors:
             allowedOrigins: 'http://localhost:4200/'
             allowedMethods: '*'
             allowedHeaders: '*'
             maxAge: 3600            
        - id : r2
          uri: http://localhost:8091/
          predicates:
            - Path=/users/**
          metadata:
           cors:
             allowedOrigins: 'http://localhost:4200/'
             allowedMethods: '*'
             allowedHeaders: '*'
             maxAge: 3600
            
            
            
  application:
    name: gateway-service
server:
  port: 8888