#spring:
  #cloud:
    #gateway:
      #default-filters:
       # - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      #globalcors:
        #corsConfigurations:
         # '[/**]':
        #    allowedOrigins: "http://localhost:4200"
       #     allowedHeaders: "*"
      #      allowedMethods: "*"

#spring:
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#             allowedOrigins: "http://localhost:4200"
#             allowedHeaders: "*"
#             allowedMethods: "*"
#      routes:
#        - id: USERS-SERVICE
#          uri: lb://USERS-SERVICE
#          predicates:
#            - Path=/users/**
#          filters:
#            - RewritePath=/irrigationapi/(?<segment>.*), /$\{segment}
#            - RemoveRequestHeader=Cookie
            
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: USERS-SERVICE
#        uri: http://localhost:8090/
#        predicates:
#        - Path=/users/**
#        metadata:
#          cors:
#            allowedOrigins: '*'
#            allowedMethods: '*'
#
#            allowedHeaders: '*'
#            maxAge: 3600

#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: USERS-SERVICE
#        uri: lb://USERS-SERVICE
#        predicates:
#        - Path=/users/**
#        metadata:
#          cors:
#            allowedOrigins: '*'
#            allowedMethods: '*'
#            allowedHeaders: '*'
#            maxAge: 30



spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://127.0.0.1:4200"
#            allowedHeaders:
#              - "Origin"
#              - "Content-Type"
#              - "Accept"
#              - "Authorization"
#              - "Referer"
#            allowedMethods:
#              - POST
#              - PUT
#              - PATCH
#              - GET
#              - OPTIONS
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
#    
#        
# spring:
#   cloud:
#     gateway:
#       globalcors:
#         cors-configurations:
#           '[/**]':
#             allowedOrigins: "*"
#             allowedMethods:
#             - GET
#             - POST