spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedHeaders:
              - Content-Type
            allow-credentials: true  
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE